CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(50) PRIMARY KEY,
  account_number VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL,
  balance NUMERIC(19,2) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  owner_id VARCHAR(50) NOT NULL
);
